version: '3.1'

services:
  project:
    build:
      .
    depends_on:
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - 8080:15672
      - 5672:5672

